#include <stdio.h>  
int main()  
{   char operation;  
    int a,b;   
    float solution;  
    printf (" Choose the number to perform a operation in the Calculator\n");
    printf("1-Multiplication");
    printf("2-Division");
    printf("3-Subtraction");
    printf("4-Addition");
    scanf ("%c", &operation); 
    if (operation == '1' )  
    {  
         printf ("Multiplication has been choosen");  
    }  
    
    else if (operation == '2')  
    {  
        printf ("Division has been choosen"); 
     }  
       
    else if (operation == '3')  
    {  
        printf ("Subtraction has been choosen");  
     }  
    else if (operation == '4')  
    {  
        printf ("Addition has been choosen");  
     }     
    
    printf (" \n Enter the first number: ");  
    scanf(" %d", &a); 
    printf (" Enter the second number: ");  
    scanf (" %d", &b); 
      
    switch(operation)  
    {  
        case '1':  
            solution = a * b;   
            printf (" Multiplication of %d and %d is: %.2f", a, b,solution);  
            break;            
          
        case '2':  
            if (b == 0)  
            {  
                printf (" \n Divisor cannot be zero. Please enter another value ");  
                scanf ("%d", &b);        
                }  
            solution = a/b;  
            printf (" Division of %d and %d is: %.2f", a, b, solution);  
            break;
        
        case '3':  
            solution = a - b;
            printf (" Subtraction of %d and %d is: %.2f", a, b, solution);  
            break; 
        
        case '4':  
            solution = a+b;   
            printf (" Addition of %d and %d is: %.2f", a, b, solution);  
            break; 
        
        default:  
            printf ("Invalid Entry");               
    }  
    return 0;  
}
